# https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/ade20k.md
python ./scripts/keras_train.py --num_gpus 1 \
                                --gpu_devices 1 \
                                --batch_size 8 \
                                --weight_decay 0.00004 \
                                --epochs 300 \
                                --initial_epoch 0 \
                                --dataset_name ade20k \
                                --dataset_dir /hdd02/zhangyiyang/data/ADE20K/tfrecord \
                                --train_split_name train \
                                --val_split_name val \
                                --max_resize_value 513 \
                                --min_resize_value 513 \
                                --crop_height 513 \
                                --crop_width 513 \
                                --min_scale_factor 0.5 \
                                --max_scale_factor 2.0 \
                                --scale_factor_step_size 0.25 \
                                --num_readers 4 \
                                --learning_policy poly \
                                --base_learning_rate 1e-4 \
                                --learning_power 0.9 \
                                --end_learning_rate 0. \
                                --training_number_of_steps 150000  \
                                --model_type deeplab_v3_plus \
                                --model_weights pascal_voc \
                                --backend_type xception \
                                --output_stride 16 \
                                --clean_model_dir \
                                --logs_name default