python ./scripts/keras_evaluate.py --num_gpus 1 \
                                   --gpu_devices 1 \
                                   --dataset_name cityscapes \
                                   --dataset_dir /hdd02/zhangyiyang/data/Cityscapes/tfrecords \
                                   --split_name val \
                                   --eval_crop_height 1025 \
                                   --eval_crop_width 2049 \
                                   --model_type deeplab_v3_plus \
                                   --backend_type xception \
                                   --output_stride 16 \
                                   --model_weights_path None \
                                   --model_weights cityscapes